### ISSUE TITLE
Commits unauthored

### ISSUE THREAD

**Issue by creativecreatorormaybenot** [mjohnsullivan/rive-by-example#1]
Hi @mjohnsullivan 😃 

First of all: it is great to see the examples; really glad you made them 🔥 

Second of all: the commits apart from the initial one are **unlinked** on GitHub.

I always feel like that looks somewhat bad on a repo. You could fix it by just adding `matt@rive.app` to your emails in the GitHub settings (that is it :D).

Just something I noticed - thanks again for the repo.

**Comment by mjohnsullivan** [comment]
Nice catch; let me go fix that ...
