### ISSUE TITLE
flutter create . doesn't work

### ISSUE THREAD

**Issue by lenniezelk** [mjohnsullivan/rive-by-example#4]
I tried running `flutter create .` in the directories `01_looping_animation`, `02_start_stop_animation` etc but i keep getting the error `"01_looping_animation" is not a valid Dart package name.` etc

Flutter 1.22.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 7891006299 (7 days ago) • 2020-12-10 11:54:40 -0800
Engine • revision ae90085a84
Tools • Dart 2.10.4

**Comment by mjohnsullivan** [comment]
I was trying to be too clever with my project folder names. Dart doesn't like packages that begin with a digit.

I'm going to rename these now to use F_XX_example_name; that should make Dart happy and ```flutter create .``` work.
